services:

  postgres:
    container_name: postgres-${BRANCH:-None}-${TAG:-None}-${COMMIT_SHORT_SHA:-None}
    image: postgres
    shm_size: 128mb
    volumes:
      - "postgres:/var/lib/postgresql:rw"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parser
    hostname: postgres
    restart: always
    networks:
      parser:
        ipv4_address: 172.40.0.2
    ports:
      - "5432:5432"

  parser:
    container_name: parser-${BRANCH:-None}-${TAG:-None}-${COMMIT_SHORT_SHA:-None}
    image: parser-${BRANCH:-None}-${TAG:-None}-${COMMIT_SHORT_SHA:-None}
    build:
      context: .
      args:
        - FILE_INN=inn.csv
    #volumes:
    volumes:
      - "parser:/usr/src/logs:rw"
    env_file:
      - path: .env
    #restart: always
    hostname: parser
    networks:
      parser:
        ipv4_address: 172.40.0.3
    depends_on: 
      - postgres

volumes:
  parser:
    external: true
  postgres:
    external: true

networks:
  parser:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
          gateway: 172.40.0.1
