"""add table KadArbitr

Revision ID: 55c3e772541d
Revises: c38d354bb066
Create Date: 2026-04-26 17:45:03.172769

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '55c3e772541d'
down_revision: Union[str, Sequence[str], None] = 'c38d354bb066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kadarbitr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.Column('name_document', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number', 'last_date', 'name_document', name='uq_case_numer_last_date_name_document')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kadarbitr')
    # ### end Alembic commands ###
