"""update

Revision ID: b22d8a0ba271
Revises: aa76ee20517b
Create Date: 2026-04-25 19:05:26.197990

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b22d8a0ba271"
down_revision: Union[str, Sequence[str], None] = "aa76ee20517b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inn", sa.Column("name_document", sa.String(), nullable=False))
    op.alter_column(
        "inn",
        "last_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inn",
        "last_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("inn", "name_document")
    # ### end Alembic commands ###
