"""update

Revision ID: 63dd6c6d86c5
Revises: 701ae2dc0f90
Create Date: 2026-04-25 19:26:12.413015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "63dd6c6d86c5"
down_revision: Union[str, Sequence[str], None] = "701ae2dc0f90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inn", "name_document", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inn", "name_document", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
