"""update Fedresurs

Revision ID: 763640d37e77
Revises: 55c3e772541d
Create Date: 2026-04-26 17:54:34.233004

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '763640d37e77'
down_revision: Union[str, Sequence[str], None] = '55c3e772541d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fedresurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn_number', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn_number', 'last_date', name='uq_inn_numb_last_date')
    )
    # op.drop_table('inn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inn',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('inn_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inn_pkey')),
    sa.UniqueConstraint('inn_number', 'last_date', name=op.f('uq_inn_numb_last_date'))
    )
    op.drop_table('fedresurs')
    # ### end Alembic commands ###
