"""INIT

Revision ID: 9184e6e5b52f
Revises: 
Create Date: 2026-04-23 21:03:33.391732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9184e6e5b52f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("CREATE DATABASE parser;")
    op.create_table('inn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('last_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inn')
    # ### end Alembic commands ###
