"""update INN

Revision ID: aa76ee20517b
Revises: 9184e6e5b52f
Create Date: 2026-04-24 15:56:29.270229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa76ee20517b'
down_revision: Union[str, Sequence[str], None] = '9184e6e5b52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inn', sa.Column('inn_number', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_inn_numb_last_date', 'inn', ['inn_number', 'last_date'])
    op.drop_column('inn', 'created_at')
    op.drop_column('inn', 'inn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inn', sa.Column('inn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inn', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_inn_numb_last_date', 'inn', type_='unique')
    op.drop_column('inn', 'inn_number')
    # ### end Alembic commands ###
